name: hacksouth
channels:
  - defaults
dependencies:
  - numpy>=1.11
  - scipy>=1.3
  - jupyter>=1.0.0
  - pandas>=0.25
  - matplotlib>=3.1.0
  - scikit-learn>=0.21
  - pip>=19.0.3
  - seaborn>=0.8
  - xlrd>=1.1.0
  - numba>=0.25